export const businessTemplates: Record<string, string[]> = {
  atta_chakki_mill: [
    "Flour mill grinder machine",
    "Stone chakki grinder",
    "Grain cleaning machine",
    "Wheat storage bins",
    "Flour packaging machine",
    "Industrial weighing scale",
    "Electrical installation",
    "Packaging materials",
  ],
  general_store: [
    "Display racks",
    "Billing counter",
    "POS system",
    "Refrigerator",
    "Storage shelves",
    "Security cameras",
    "Lighting fixtures",
    "Inventory software",
  ],
  cafe: [
    "Espresso machine",
    "Coffee grinder",
    "Commercial blender",
    "Cake display fridge",
    "Dining tables",
    "Chairs",
    "Kitchen stove",
    "Deep fryer",
  ],
  paper_plate_business: [
    "Paper plate making machine",
    "Semi automatic paper plate machine",
    "Automatic paper plate machine",
    "Paper plate die",
    "Paper plate raw material",
    "Paper plate packaging machine",
    "Paper plate weighing scale",
    "Paper plate electrical installation",
    "Paper plate packaging materials",
  ],
  paper_cup_business: [
    "Paper cup making machine",
    "Semi automatic paper cup machine",
    "Automatic paper cup machine",
    "Paper cup die",
    "Paper cup raw material",
    "Paper cup packaging machine",
    "Paper cup weighing scale",
    "Paper cup electrical installation",
    "Paper cup packaging materials",
  ],
  paper_napkin_business: [
    "Paper napkin making machine",
    "Semi automatic paper napkin machine",
    "Automatic paper napkin machine",
    "Paper napkin die",
    "Paper napkin raw material",
    "Paper napkin packaging machine",
    "Paper napkin weighing scale",
    "Paper napkin electrical installation",
    "Paper napkin packaging materials",
  ],
  paper_glass_business: [
    "Paper glass making machine",
    "Semi automatic paper glass machine",
    "Automatic paper glass machine",
    "Paper glass die",
    "Paper glass raw material",
    "Paper glass packaging machine",
    "Paper glass weighing scale",
    "Paper glass electrical installation",
    "Paper glass packaging materials",
  ],
};

export const getTemplateByBusinessType = (type: string): string[] | null => {
  // Normalize type string
  const normalized = type.toLowerCase().replace(/\s+/g, "_");
  return businessTemplates[normalized] || businessTemplates["atta_chakki_mill"]; // Default to atta chakki if not found
};
